name: Build LaTeX document

on:
  push:
    branches: [main]

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v1

      - name: Install hexo-cli and deps
        run: |
          npm install hexo-cli -g && npm i

      - name: Build hexo
        run: |
          hexo g

      - name: Push to gh-pages
        if: success() && github.event_name == 'push'
        uses: peaceiris/actions-gh-pages@068dc23d9710f1ba62e86896f84735d869951305
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public